### ISSUE TITLE
Need help with the binary - content-android-resources-v1.0.0.aar 

### ISSUE THREAD

**Issue by snehilrx** [wuruxu/crwebview#6]
Hi @wuruxu, 

I cannot compile the project because I lack access to a Linux machine. It would greatly assist me if you could include "content-android-resources-v1.0.0.aar" in a new release. 

Thank you very much for developing this project.

**Comment by wuruxu** [comment]
I'm a bit busy in this month, but I'll find a way to upgrade crwebview to chromium v125 next month.

**Comment by snehilrx** [comment]
Thank you for your prompt response. In the meantime, I'll explore managing my use case using a webview.

**Comment by snehilrx** [comment]
The problem I encountered during the library integration was due to forgetting to include implementation 'androidx.appcompat:appcompat:1.7.0' in the build.gradle file.
